id = "mdsl"
name = "mdsl"
description = "mdsl support"
version = "0.5.14"
schema_version = 1
authors = ["dvsmc <dvsmc@pm.me>"]
repository = "https://github.com/dvsmc/zed-mdsl"

[grammars.mdsl]
repository = "https://github.com/dvsmc/tree-sitter-mdsl"
commit = "7eab08b824d5344d1283aed94bf5592aa4c29abb"

[language_servers.mdsl]
name = "mdsl"
language = "mdsl"
