id = "mdsl"
name = "mdsl"
description = "mdsl support"
version = "0.3.0"
schema_version = 1
authors = ["dvsmc <dvsmc@pm.me>"]
repository = "https://github.com/dvsmc/zed-mdsl"

[grammars.mdsl]
repository = "https://github.com/dvsmc/tree-sitter-mdsl"
commit = "ebaeb373e443dec0f945493a5a6bb9c9d0a743f8"

[language_servers.mdsl]
name = "mdsl"
language = "mdsl"
