id = "mdsl"
name = "mdsl"
description = "mdsl support"
version = "0.5.6"
schema_version = 1
authors = ["dvsmc <dvsmc@pm.me>"]
repository = "https://github.com/dvsmc/zed-mdsl"

[grammars.mdsl]
repository = "https://github.com/dvsmc/tree-sitter-mdsl"
commit = "2b4c149642a8d1acf0232d9532b7a53d2e11f945"

[language_servers.mdsl]
name = "mdsl"
language = "mdsl"
