id = "mdsl"
name = "mdsl"
description = "mdsl support"
version = "0.5.2"
schema_version = 1
authors = ["dvsmc <dvsmc@pm.me>"]
repository = "https://github.com/dvsmc/zed-mdsl"

[grammars.mdsl]
repository = "https://github.com/dvsmc/tree-sitter-mdsl"
commit = "84d53de4bf84b8da486a36dbd07b55eb92115ef1"

[language_servers.mdsl]
name = "mdsl"
language = "mdsl"
