id = "mdsl"
name = "mdsl"
description = "mdsl support"
version = "0.5.10"
schema_version = 1
authors = ["dvsmc <dvsmc@pm.me>"]
repository = "https://github.com/dvsmc/zed-mdsl"

[grammars.mdsl]
repository = "https://github.com/dvsmc/tree-sitter-mdsl"
commit = "4bcd4315ebeae40ab0e8790a17e39ec8354263fd"

[language_servers.mdsl]
name = "mdsl"
language = "mdsl"
