id = "mdsl"
name = "mdsl"
description = "mdsl support"
version = "0.5.12"
schema_version = 1
authors = ["dvsmc <dvsmc@pm.me>"]
repository = "https://github.com/dvsmc/zed-mdsl"

[grammars.mdsl]
repository = "https://github.com/dvsmc/tree-sitter-mdsl"
commit = "05c84991339d6d0132de13f651a9ed46a45c9af1"

[language_servers.mdsl]
name = "mdsl"
language = "mdsl"
