name = "mdsl"
scope = "source.mdsl"

# Patterns to highlight
patterns = [
    { match = "\\b(root|sequence|selector|parallel|race|all|lotto|repeat|retry|flip|succeed|fail|action|condition|wait|branch|entry|exit|step|while|until)\\b", scope = "keyword.control.mdsl" },
  
  # Match identifiers for functions/entities (alphanumeric with underscores)
  { match = "\\b[a-zA-Z_][a-zA-Z0-9_]*\\b", scope = "entity.name.function.mdsl" },
  
  { match = "\"[^\"]*\"", scope = "string.quoted.double.mdsl" },
  { match = "\\[(.*?)\\]", scope = "meta.brackets.mdsl" },
  { match = "\\{", scope = "punctuation.section.block.begin.mdsl" },
  { match = "\\}", scope = "punctuation.section.block.end.mdsl" },
  { match = "\\d+", scope = "constant.numeric.mdsl" }
]
